$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path;$results=@();$failed=0
function Test-Case([string]$Name,[scriptblock]$Body){$sw=[Diagnostics.Stopwatch]::StartNew();try{&$Body;$script:results+=[pscustomobject]@{Name=$Name;Result='PASS';Ms=$sw.ElapsedMilliseconds}}catch{$script:failed=1;$script:results+=[pscustomobject]@{Name=$Name;Result="FAIL: $_";Ms=$sw.ElapsedMilliseconds}}}
function Expect-Exit([int]$Expected,[scriptblock]$Body){&$Body;if($LASTEXITCODE -ne $Expected){throw "expected exit $Expected, got $LASTEXITCODE"}}
function Invoke-Hook([string]$Script,[string]$Json){$payload=Join-Path ([IO.Path]::GetTempPath()) ("relay-payload-"+[guid]::NewGuid()+'.json');Set-Content -LiteralPath $payload -Value $Json -NoNewline -Encoding UTF8;try{$oldEap=$ErrorActionPreference;$ErrorActionPreference='SilentlyContinue';Get-Content -LiteralPath $payload -Raw|powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script 2>$null;$code=$LASTEXITCODE;$ErrorActionPreference=$oldEap;return $code}finally{Remove-Item -LiteralPath $payload -Force}}
Test-Case 'settings JSON and safe PowerShell hook args' { $s=Get-Content "$root/.claude/settings.json" -Raw|ConvertFrom-Json;$raw=Get-Content "$root/.claude/settings.json" -Raw;if($raw -match "'[^']*\$\{CLAUDE_PROJECT_DIR\}[^']*'"){throw 'single-quoted project placeholder'};$hooks=@();foreach($group in @($s.hooks.PreToolUse,$s.hooks.Stop,$s.hooks.SessionEnd)){foreach($entry in @($group)){$hooks+=@($entry.hooks)}};foreach($h in $hooks){if($h.command -ne 'powershell.exe' -or -not $h.args -or -not $h.timeout){throw 'unsafe hook shape'}} }
Test-Case 'Ultracode orchestration is unrestricted' { $s=Get-Content "$root/.claude/settings.json" -Raw|ConvertFrom-Json;if('Agent' -notin @($s.permissions.allow)){throw 'Agent tool is not generally allowed'};if('Agent' -in @($s.permissions.deny)){throw 'Agent tool is denied'};$policy=Get-Content "$root/.claude/workflow-policy.yml" -Raw;foreach($entry in @('mode: ultracode','effort: xhigh','dynamic_workflows: unrestricted','agent_teams: unrestricted','background_tasks: unrestricted','repository_numeric_limits: none')){if(-not $policy.Contains($entry)){throw "missing Ultracode policy: $entry"}};foreach($skill in @('deliver-spec','deliver-sprint','close-sprint','security-assurance')){if(-not(Test-Path "$root/.claude/skills/$skill/SKILL.md")){throw "missing machine skill: $skill"}} }
Test-Case 'workflow guides cover independent assurance roles' { foreach($guide in @("$root/docs/manual/operational/en-US/WORKFLOW-GUIDE.md","$root/docs/manual/operational/pt-BR/WORKFLOW-GUIDE.md")){if(-not(Test-Path $guide)){throw "missing workflow guide: $guide"};$text=Get-Content -Raw -Encoding utf8 $guide;foreach($worker in @('qa-engineer','pr-reviewer','security-assurance-engineer')){if(-not $text.Contains("### ``$worker``")){throw "guide missing worker section: $worker"}};foreach($command in @('/deliver-spec','/deliver-sprint','/close-sprint')){if(-not $text.Contains($command)){throw "guide missing top-level command: $command"}}} }
Test-Case 'all workflow skills are manual' { $bad=Get-ChildItem "$root/.claude/skills" -Filter SKILL.md -Recurse|Where-Object{(Get-Content $_.FullName -Raw)-notmatch '(?m)^disable-model-invocation:\s*true\s*$'};if($bad){throw "automatic skill: $($bad.FullName)"} }
Test-Case 'structured spec frontmatter' { Push-Location $root;powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$root/tools/workflow/validate-specs.ps1";if($LASTEXITCODE -ne 0){throw 'spec validator failed'};Pop-Location }
Test-Case 'English-only repository artifacts' { Push-Location $root;powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$root/tools/workflow/validate-doc-language.ps1";if($LASTEXITCODE -ne 0){throw 'documentation language validator failed'};Pop-Location }
Test-Case 'deterministic cross-state spec approval hash' { $spec=(Get-ChildItem "$root/docs/specs" -File | Where-Object{$_.Name -match '^SPEC-[0-9]{4}-'} | Select-Object -First 1).FullName;if(-not $spec){throw 'no spec to hash'};$a=(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$root/tools/workflow/spec-hash.ps1" -SpecPath $spec).Trim();$copy=Join-Path ([IO.Path]::GetTempPath()) ("relay-spec-"+[guid]::NewGuid()+'.md');try{$text=[IO.File]::ReadAllText($spec,[Text.UTF8Encoding]::new($false)).Replace("`r`n","`n");$text=$text -replace '(?m)^owner_approved_at:.*$','owner_approved_at: 2026-07-17T00:00:00Z' -replace '(?m)^owner_approved_hash:.*$','owner_approved_hash: abc';[IO.File]::WriteAllText($copy,$text.Replace("`n","`r`n"),[Text.UTF8Encoding]::new($false));$b=(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$root/tools/workflow/spec-hash.ps1" -SpecPath $copy).Trim();if($a -ne $b -or $a -notmatch '^[0-9a-f]{64}$'){throw 'approval hash is not deterministic'}}finally{Remove-Item -LiteralPath $copy -Force -ErrorAction SilentlyContinue} }
$tmp=Join-Path ([IO.Path]::GetTempPath()) ("relay-smoke-"+[guid]::NewGuid());New-Item -ItemType Directory -Force "$tmp/.claude/runtime/SPEC-0099"|Out-Null
try{$old=$env:CLAUDE_PROJECT_DIR;$env:CLAUDE_PROJECT_DIR=$tmp
  Test-Case 'path guard role boundaries' { Set-Content "$tmp/.claude/runtime/current-role" designer -NoNewline;$ok='{"tool_input":{"file_path":"'+($tmp.Replace('\','/'))+'/.claude/runtime/SPEC-0099/state.json"}}';if((Invoke-Hook "$root/.claude/hooks/path-guard.ps1" $ok)-ne 0){throw 'designer runtime rejected'};$bad='{"tool_input":{"file_path":"'+($tmp.Replace('\','/'))+'/backend/App.java"}}';if((Invoke-Hook "$root/.claude/hooks/path-guard.ps1" $bad)-ne 2){throw 'designer production accepted'} }
  Test-Case 'shell guard blocks mutation bypasses' { foreach($c in @('git merge develop','gh pr merge 1','Set-Content backend/App.java x','python -c "open(''backend/x'',''w'')"')){$json=@{tool_input=@{command=$c}}|ConvertTo-Json -Compress;if((Invoke-Hook "$root/.claude/hooks/shell-guard.ps1" $json)-ne 2){throw "accepted: $c"}} }
  Test-Case 'stop guard terminal contract' { Set-Content "$tmp/.claude/runtime/current-slice" SPEC-0099 -NoNewline;'{"slice":"SPEC-0099","status":"BUILDING"}'|Set-Content "$tmp/.claude/runtime/SPEC-0099/state.json" -NoNewline;if((Invoke-Hook "$root/.claude/hooks/stop-guard.ps1" '{}')-ne 2){throw 'in-progress accepted'};'[]'|Set-Content "$tmp/.claude/runtime/SPEC-0099/metrics.json";'{"slice":"SPEC-0099","status":"DEV_VERIFIED"}'|Set-Content "$tmp/.claude/runtime/SPEC-0099/state.json";if((Invoke-Hook "$root/.claude/hooks/stop-guard.ps1" '{}')-ne 0){throw 'terminal rejected'};if((Invoke-Hook "$root/.claude/hooks/stop-guard.ps1" 'not-json')-ne 2){throw 'invalid JSON accepted'} }
}finally{$env:CLAUDE_PROJECT_DIR=$old;Remove-Item -LiteralPath $tmp -Recurse -Force}
$results|Format-Table -AutoSize;if($failed){exit 1};"relay-smoke: PASS ($($results.Count) tests)"
