-- V1 - baseline marker for the walking skeleton (SPEC-0018, OR-4).
--
-- This migration intentionally creates NO business tables. The first ones arrive with their
-- owning specifications: the chart of accounts and postings with SPEC-0001 (ledger core), the
-- customer and account tables with SPEC-0002 (sign-up and account).
--
-- Its purpose is to prove the migration pipeline end to end: Flyway connects, applies, and
-- records history against the real PostgreSQL 16 the application runs on. FlywayBaselineIT
-- asserts exactly one applied migration with success = true.
--
-- An applied migration is immutable. Do not edit this file to change the schema; add a new
-- one (OR-4).

-- Timestamps are stored in UTC across the schema; timezone is a presentation-edge concern.
-- Recorded here as executable documentation of the convention every later migration follows.
COMMENT ON SCHEMA public IS 'FKBANK - all timestamps stored in UTC (SPEC-0018 OR-4)';
