-- The accounting core: the chart of accounts, the postings that move money between them, and
-- the running balance each account holds.
--
-- The schema is written so that the states the ledger must never reach are impossible here, not
-- merely discouraged in Java. Application code can be bypassed by a migration, a support script
-- or a future mistake; a trigger and a unique index cannot.
--
-- All timestamps are UTC.

-- An account in the chart of accounts. Reference data for the internal accounts, seeded below;
-- customer and box accounts are opened as people and boxes are created.
CREATE TABLE account (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT        NOT NULL UNIQUE,
    kind        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT account_kind_known CHECK (kind IN (
        'CUSTOMER_AVAILABLE',
        'CUSTOMER_BOX',
        'INTERNAL_SETTLEMENT',
        'INTERNAL_EXPENSE',
        'INTERNAL_CREDIT'
    ))
);

COMMENT ON TABLE account IS
    'Chart of accounts. Id order is the order balance locks are acquired in.';

-- One movement of money. Append-only: see the trigger below.
CREATE TABLE posting (
    id                  UUID        PRIMARY KEY,
    debit_account_id    BIGINT      NOT NULL REFERENCES account (id),
    credit_account_id   BIGINT      NOT NULL REFERENCES account (id),
    amount              NUMERIC(19, 4) NOT NULL,
    currency            VARCHAR(3)  NOT NULL,
    occurred_at         TIMESTAMPTZ NOT NULL,
    reverses_posting_id UUID        REFERENCES posting (id),
    CONSTRAINT posting_amount_positive CHECK (amount > 0),
    CONSTRAINT posting_between_two_accounts CHECK (debit_account_id <> credit_account_id)
);

COMMENT ON TABLE posting IS
    'Append-only double-entry movements. Corrections are contra-postings, never edits.';

CREATE INDEX posting_debit_account_idx ON posting (debit_account_id);
CREATE INDEX posting_credit_account_idx ON posting (credit_account_id);

-- A posting is reversed at most once.
--
-- The ledger refuses a second reversal before it gets here, but that check reads the table and
-- then writes to it: two concurrent reversals can both read "not yet reversed". This index is
-- what makes the second one fail. Without it, the extra contra-posting would land on an account
-- allowed to go negative, producing a balance that is fabricated yet perfectly self-consistent -
-- invisible to a trial balance, because debits would still equal credits.
CREATE UNIQUE INDEX posting_reverses_at_most_once_idx
    ON posting (reverses_posting_id)
    WHERE reverses_posting_id IS NOT NULL;

-- A reversal never points at itself.
ALTER TABLE posting ADD CONSTRAINT posting_does_not_reverse_itself
    CHECK (reverses_posting_id IS NULL OR reverses_posting_id <> id);

-- Immutability, enforced where it cannot be argued with.
CREATE OR REPLACE FUNCTION posting_is_append_only() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'posting is append-only: % on posting is not permitted', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER posting_no_update_or_delete
    BEFORE UPDATE OR DELETE ON posting
    FOR EACH ROW EXECUTE FUNCTION posting_is_append_only();

-- TRUNCATE is not a DELETE as far as triggers are concerned: it removes every row without
-- firing a row-level trigger even once, so the guard above would watch an empty table being
-- emptied. It needs its own statement-level trigger, or one statement erases the ledger.
CREATE TRIGGER posting_no_truncate
    BEFORE TRUNCATE ON posting
    FOR EACH STATEMENT EXECUTE FUNCTION posting_is_append_only();

-- What an account currently holds.
--
-- A convenience, not the truth: the postings are the truth. Keeping it saved avoids replaying an
-- account's entire history on every read, and the trial balance exists to prove the two still
-- agree. Rows are locked FOR UPDATE, in ascending account id order, while a posting is applied.
CREATE TABLE balance (
    account_id BIGINT      PRIMARY KEY REFERENCES account (id),
    amount     NUMERIC(19, 4) NOT NULL,
    currency   VARCHAR(3)  NOT NULL
);

COMMENT ON TABLE balance IS
    'Materialized balance per account, verified against the postings by the trial balance.';

-- The internal side of the chart of accounts. Customer and box accounts are opened on demand.
INSERT INTO account (code, kind) VALUES
    ('internal:settlement:boleto',  'INTERNAL_SETTLEMENT'),
    ('internal:settlement:pix',     'INTERNAL_SETTLEMENT'),
    ('internal:settlement:card',    'INTERNAL_SETTLEMENT'),
    ('internal:expense:yield',      'INTERNAL_EXPENSE'),
    ('internal:credit:disbursement','INTERNAL_CREDIT');

INSERT INTO balance (account_id, amount, currency)
SELECT id, 0, 'BRL' FROM account;

-- Persistent event publication registry: the outbox base.
--
-- Owned by Flyway rather than auto-created at startup, so the shape of a table that will hold
-- unprocessed business facts is reviewed like any other schema change.
-- Mirrors the framework's own PostgreSQL schema (v2). Kept identical on purpose: the framework
-- reads and writes these columns, so a well-meaning improvement here would break it at startup.
CREATE TABLE event_publication (
    id                     UUID        NOT NULL PRIMARY KEY,
    listener_id            TEXT        NOT NULL,
    event_type             TEXT        NOT NULL,
    serialized_event       TEXT        NOT NULL,
    publication_date       TIMESTAMPTZ NOT NULL,
    completion_date        TIMESTAMPTZ,
    status                 TEXT,
    completion_attempts    INT,
    last_resubmission_date TIMESTAMPTZ
);

CREATE INDEX event_publication_serialized_event_hash_idx
    ON event_publication USING hash (serialized_event);
CREATE INDEX event_publication_by_completion_date_idx
    ON event_publication (completion_date);
